import { jsPDF } from 'jspdf';

/**
 * Draws the standard page footer text based on document type.
 */
export function buildPdfFooter(
  doc: jsPDF,
  type: 'estimate' | 'invoice' | 'receipt' | 'workorder'
): void {
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.setFont(undefined as unknown as string, 'normal');

  let mainText: string;
  if (type === 'invoice') {
    mainText = 'Thank you for your business. Payment is due upon receipt.';
  } else if (type === 'receipt') {
    mainText = 'Thank you for your payment!';
  } else if (type === 'workorder') {
    mainText = 'Internal use only. Not for customer distribution.';
  } else {
    mainText =
      'This is an estimate only. Actual material usage may vary based on site conditions.';
  }

  doc.text(mainText, pageWidth / 2, pageHeight - 15, { align: 'center' });
  doc.text('Generated by RFE Foam Pro', pageWidth / 2, pageHeight - 10, {
    align: 'center',
  });
}
